### PR TITLE
fix: hook fails silently on `yarn add` during update of plugins

### LINKED ISSUE #76: update hook fails silently on `yarn add` errors
`mycli update` triggers the `plugins:update` command, if the `plugins:update` fails on installation of a new plugin `yarn add ...`, then the update fails silently.

`mycli plugins:update` however displays the error as expected.

### Assumed root cause
The `update` hook is not catching error which makes the CLI update fails silently.

### PR DESCRIPTION
**Pull request by ArchangelX360**
Fixes #76

### CODE REVIEW

File: src/hooks/update.ts [hunk 1]
```diff
@@ -4,5 +4,9 @@ import Plugins from '../plugins'
 
 export const update: Hook<'update'> = async function () {
   const plugins = new Plugins(this.config)
-  await plugins.update()
+  try {
+    await plugins.update()
+  } catch (e) {
+    this.error(e)
```
Comment (RasPhilCo) [inline src/hooks/update.ts:10]:
```suggestion
  } catch (error) {
    this.error(error.message)
```

Comment (RasPhilCo) [reply src/hooks/update.ts:10]: The error pretty prints better & the stack trace largely useless here.

Comment (RasPhilCo) [reply src/hooks/update.ts:10]: Let me know if you object!

Comment (ArchangelX360) [reply src/hooks/update.ts]: Hey, sorry for the delay.
I usually prefer to let the command logger do the truncation/alteration choices, thus giving it the full error object.
It gives more flexibility to users that would have extended `Command` to have their own base `Command` class, with some custom logging things.

For example, in my company, we are wiring the error logging to our company-wide observability systems, it is valuable to have the Error object instead of just a string to extract full context.
